export const actions = {
    profile:{
        DATA_FETCHING: "PROFILE_DATA_FETCHING",
        DATA_FETCHED: "PROFILE_DATA_FETCHED",
        DATA_FETCHING_ERROE: "PROFILE_DATA_FETCHING_ERROR",
        USER_DATA_EDITED: "PROFILE_USER_EDATED",
        IMAGE_UPDATED:"PROFILE_IMAGE_UPDATED"
    }
}